@startuml
class SpawnTile {
    + maxDistanceFromPlayer : float = 0.5f
    + distanceBetweenTiles : float = 5.0f
    + randomValue : float = 0.7f
    + obstacleSpawnRate : float = 0.1f
    + changePlayer(p:GameObject) : void
    Start() : void
    Update() : void
}
MonoBehaviour <|-- SpawnTile
SpawnTile --> "tileToSpawn" GameObject
SpawnTile --> "referenceObject" GameObject
SpawnTile --> "player" GameObject
SpawnTile --> "groundToSpawn" GameObject
SpawnTile --> "coinPrefab" GameObject
SpawnTile --> "PowerUpScorePrefab" GameObject
SpawnTile --> "SlowDownPrefab" GameObject
SpawnTile --> "obstaclePrefab" GameObject
@enduml
