@startuml
class Player {
    + {static} setName(val:string) : void
    + setPlayerMovement(val:PlayerMovement) : void
    + {static} getName() : string
    + {static} getMoney() : int
    + {static} getScore() : float
    + {static} UpdateMoney(amount:int) : void
    + {static} UpdateScore(amount:float) : void
    Start() : void
    Update() : void
    checkDeath() : void
}
MonoBehaviour <|-- Player
@enduml
