@startuml
class PlayerMovement {
    + jumpSpeed : float = 10.0f
    + setSpeed(val:float) : void
    + getSpeed() : float
    + slowdown() : void
    Start() : void
    Update() : void
}
MonoBehaviour <|-- PlayerMovement
@enduml
