name: Unity Test Runner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Unity packages
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('**/Packages/manifest.json') }}
          restore-keys: |
            Library-${{ runner.os }}-

      - name: Setup Unity License
        uses: game-ci/unity-activate@v3.2.2 # Use the latest version from GitHub Marketplace or documentation
        with:
          unityLicense: ${{ secrets.UNITY_LICENSE }}

      - name: Unity - Test runner
        uses: game-ci/unity-test-runner@v3.1.0 # Use the latest version from GitHub Marketplace or documentation
        with:
          projectPath: ./TempleRun/ # Root directory where the Unity project is located
          testMode: editmode # Specify that we want to run Edit Mode tests
          artifactsPath: artifacts # Where to store test results
          unityVersion: auto # Use the Unity version specified in ProjectSettings/ProjectVersion.txt

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: Test Results
          path: artifacts
